version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  remote-interpreter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command:
      [
        "./scripts/start-development.sh",
      ]
  tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-tests.sh"]
  lint:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-lint.sh"]
