# Generated by Django 3.1.7 on 2021-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('word_or_symbol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phoneset',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('phoneme', models.CharField(blank=True, max_length=100, null=True)),
                ('phonemic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phonemic transcription')),
                ('phonetic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phonetic transcription')),
                ('words_or_symbols', models.ManyToManyField(related_name='transcription', to='core.Dictionary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
