# Generated by Django 3.1.7 on 2021-03-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('classification', models.CharField(choices=[('NOUN', 'Noun'), ('PRONOUN', 'Pronoun'), ('ADJECTIVE', 'Adjectives'), ('VERB', 'Verb'), ('ADVERB', 'Adverbs'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('SYMBOL', 'Symbol')], max_length=15)),
                ('word_or_symbol', models.CharField(max_length=45, unique=True)),
                ('phoneme', models.CharField(blank=True, max_length=100, null=True)),
                ('phonemic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phonemic transcription')),
                ('phonetic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phonetic transcription')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='core.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
